### ISSUE TITLE
Enhancement idea!

### ISSUE THREAD

**Issue by AseKarlsson** [cokeman0/OpenEpaperElectricPriceTag#10]
Hi,

I maybe could solve this my self if I put my heart into the code, but thought this could be easy code modification for you that is the author!

Could you also adjust the code to show the next 12 hours, idea here is to put 2 pieces of 2.9" displays next to each other to show the whole 24h.

Display 1 (left) the first 12 hours like the code today
Display 2 (right) the last 12 hours 

Thanks,
Ase

**Comment by cokeman0** [comment]
Hi,

You need setup 2 diffrent versions of the code, and remove 12 hours from the both codes.

you can adjust with and spacing using the variables
