### ISSUE TITLE
Hourly update issue

### ISSUE THREAD

**Issue by AseKarlsson** [cokeman0/OpenEpaperElectricPriceTag#9]
Hi,
Nice integration with Nordpool and OpenEpaperLink!
Got everything working nice with the code, but wonder why the hourly updated stacks are not filled with color and are empty instead?
![image](https://github.com/cokeman0/OpenEpaperElectricPriceTag/assets/80900477/3dbe1e09-3693-4ae5-b8ce-c6440af8e58c)

**Comment by cokeman0** [comment]
Red, Expensive
Black, middle
Empty, low

So the eye will catch the right price segment faster :-)

**Comment by AseKarlsson** [comment]
Had minus prices before today, so this was the first time seeing this! Thanks a lot for a Great Integration!

**Comment by cokeman0** [comment]
your are welcome :-D
